#!/bin/bash

### global constants ###

NEWTABWINDOWNAME="my home page — Mozilla Firefox"

CLOSEADDRESSBARHISTORY=true			# simulates a escape key press after ctrl+l


### script ###

# if window name is correct press ctrl+l and escape afterwards
changeDetected() {
	eval newWindow="$1"
	if [[ "$newWindow" == "$NEWTABWINDOWNAME" ]]
	then
		echo "focusing address bar"
		sleep 0.05
		checkWindow=$(xdotool getactivewindow getwindowname)
		if [[ "$checkWindow" == "$NEWTABWINDOWNAME" ]]
		then
			xdotool key --clearmodifiers ctrl+l	# focus address bar
			if $CLOSEADDRESSBARHISTORY
			then
				xdotool key --clearmodifiers Escape	# close address bar history
			fi
		fi
	fi
}

# check active windows for change
activeWindow=null
while true
do	
	newWindow=$(xdotool getactivewindow getwindowname)
	if [[ "$newWindow" != "$activeWindow" ]]
	then
		activeWindow=$newWindow
		echo $activeWindow
		changeDetected "\${newWindow}"		
				# "\  " needed together with eval arg1="$1" in order to be able to pass spaces in the argument as one argument
	fi
	sleep 0.01
done
